; Generated by aseprite2bin.py for names
Sprite_Names@Data: .incbin "resources/sprites/names/names.sprite"
.define Sprite_Names@Tag@Mav                     $A14 ; 2580
.define Sprite_Names@Tag@Ice                     $A52 ; 2642
.define Sprite_Names@Tag@Vip                     $AF6 ; 2806
.define Sprite_Names@Tag@Goose                   $B67 ; 2919
.define Sprite_Names@Bank                        6