; Generated by aseprite2bin.py for boss
Sprite_Boss@Data: .incbin "resources/sprites/boss/boss.sprite"
.define Sprite_Boss@Tag@Idle                     $1C05 ; 7173
.define Sprite_Boss@Bank                         4