; Generated by aseprite2bin.py for 8x8
Sprite_8X8@Data: .incbin "resources/sprites/8x8/8x8.sprite"
.define Sprite_8X8@Tag@Idle                      $805 ; 2053
.define Sprite_8X8@Bank                          3