; Generated by aseprite2bin.py for plane
Sprite_Plane@Data: .incbin "resources/sprites/plane/plane.sprite"
.define Sprite_Plane@Tag@Forward                 $1C19 ; 7193
.define Sprite_Plane@Tag@Forward_Afterburner     $1C50 ; 7248
.define Sprite_Plane@Tag@Supersonic              $1DB4 ; 7604
.define Sprite_Plane@Tag@Bank                    $1F6F ; 8047
.define Sprite_Plane@Tag@Bank_Afterburner        $1FA6 ; 8102
.define Sprite_Plane@Bank                        3