; Generated by aseprite2bin.py for 16x16
Sprite_16X16@Data: .incbin "resources/sprites/16x16/16x16.sprite"
.define Sprite_16X16@Tag@Idle                    $805 ; 2053
.define Sprite_16X16@Bank                        3